services:
  - type: web
    name: codegenius-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://codegenius-evolve-5r3iyttko-rushikeshs-projects-8d5b90eb.vercel.app,http://localhost:8080,http://localhost:8081,http://localhost:8082
    healthCheckPath: /
    autoDeploy: true 