services:
  - type: web
    name: codegenius-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: OPENROUTER_API_KEY
        value: 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
    healthCheckPath: /
    autoDeploy: true 